### ISSUE TITLE
conda enviroment missing

### ISSUE THREAD

**Issue by SielyTicse** [JMMP-Group/pySBC#1]
While exploring resources related to the NEMO model, I came across this repo. I would greatly appreciate it if you could provide insights into the requisite execution environment and the specific version of Python that works best with your repo.

**Comment by rdPatmore** [comment]
Hi, I have added a yml file for use with a conda environment. That should get you some scripts to use with this repo. There is a line of code in the README for using the yml.

**Comment by SielyTicse** [comment]
Hi rdPatmore, thanks for the new fixes in your repository. However, I ran nemo without the latitude and longitude mesh reorganization and I had no problems, maybe you could try removing this in your code.

**Comment by rdPatmore** [comment]
No problem. Are you referring to lines 205-215 in gen_era5.py? E.g.:
```
# mesh lat and lon
mlon, mlat = np.meshgrid(da.longitude, da.latitude)
lon_attrs={'long_name':'longitude','units':'degrees_east'}
lat_attrs={'long_name':'latitude', 'units':'degrees_north'}
mlon = xr.DataArray(mlon, dims=['Y','X'], attrs=lon_attrs)
mlat = xr.DataArray(mlat, dims=['Y','X'], attrs=lat_attrs)

# assign X/Y as indexes
da = da.drop(['longitude','latitude'])
da = da.rename({'longitude':'X','latitude':'Y'})
da = da.assign_coords({'longitude':mlon,'latitude':mlat})
```
Does this assignment cause issues for your NEMO run when it is present?

**Comment by SielyTicse** [comment]
yes it is

**Comment by rdPatmore** [comment]
Ok, thanks for pointing this out. I'll do a quick check for obvious problems with the assignment before I remove it. I think it's useful to have lat/lon coordinates, if I can get them to work. I'll create a new issue.
